version: '3.8'

services:
  # Room database (PostgreSQL)
  room-db:
    image: postgres:latest
    container_name: room-db
    environment:
      POSTGRES_DB: roomdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"  # Exposing PostgreSQL to localhost on port 5432
    volumes:
      - roomdb-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  # Booking database (MongoDB)
  booking-db:
    image: mongo:latest
    container_name: booking-db
    ports:
      - "27017:27017"  # Exposing MongoDB to localhost on port 27017
    volumes:
      - bookingdb-data:/data/db
    networks:
      - microservices-network

  # User database (PostgreSQL)
  user-db:
    image: postgres:latest
    container_name: user-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5433:5432"  # Exposing PostgreSQL to localhost on port 5433
    volumes:
      - userdb-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  # Event database (MongoDB)
  event-db:
    image: mongo:latest
    container_name: event-db
    ports:
      - "27018:27017"  # Exposing MongoDB to localhost on port 27018
    volumes:
      - eventdb-data:/data/db
    networks:
      - microservices-network

  # Approval database (MongoDB)
  approval-db:
    image: mongo:latest
    container_name: approval-db
    ports:
      - "27019:27017"  # Exposing MongoDB to localhost on port 27019
    volumes:
      - approvaldb-data:/data/db
    networks:
      - microservices-network

volumes:
  roomdb-data:
  bookingdb-data:
  userdb-data:
  eventdb-data:
  approvaldb-data:

networks:
  microservices-network:
    driver: bridge
